### ISSUE TITLE
How do i create a graphql schema for a self referencing data hierarchy?

### ISSUE THREAD

**Issue by creactiviti** [andimarek/graphql-java#107]
"A GraphQL type can refer to itself (or refer to another type defined later in a file) by defining fields as a function that returns an object rather than an object. The function will be called after the page has been fully parsed." 

JS Example:

```
var routeType = new GraphQLObjectType({
  name: 'MessageRoute',
  fields: function () {
    return {
      name: {
        type: GraphQLString
      },
      routes: {
        type: new GraphQLList(routeType),
        resolve: (route) => {
          return route.routes;
        }
      }
    };
  }
});
```

Is there a `graphql-java` equivalent?

**Comment by andimarek** [comment]
You can do this with the `GraphQLTypeReference` class: https://github.com/andimarek/graphql-java#recursive-type-references
