### ISSUE TITLE
Schema.json

### ISSUE THREAD

**Issue by shankarRaman** [andimarek/graphql-java#109]
Hi Andreas,
Great work on setting this up. I have a question about the "schema.json" file- how did you generate that file? Did you manually create it?

**Comment by andimarek** [comment]
A schema.json is generated as a result of an introspection query against a server. The query can be found here: https://github.com/graphql/graphql-js/blob/master/src/utilities/introspectionQuery.js

**Comment by shankarRaman** [comment]
So when I create a new server side schema, does the "schema.json" get automatically generated (which I am not seeing) or I need to do something?

**Comment by andimarek** [comment]
No ... this schema.json it totally out of scope of the responsibility of graphql-java. How and when you generate it is up to you.

Please consider asking those question in the future at the mailing-list (https://groups.google.com/forum/#!forum/graphql-java): This is the better for this general how-to-use problems.

Thanks
Andi

**Comment by shankarRaman** [comment]
Ok thanks.
