### ISSUE TITLE
ConnectionCursor gets serialized into invalid value

### ISSUE THREAD

**Issue by hannesj** [andimarek/graphql-java#14]
When using the provided helpers for Relay, the ConnectionCursor gets serialized into an invalid value, as ConnectionCursor#toString() is used for serialization. This results that the first cursor is `"ConnectionCursor{value='c2ltcGxlLWN1cnNvcjA='}"` instead of `c2ltcGxlLWN1cnNvcjA=`

**Comment by andimarek** [comment]
I'm not sure I understand this ... which serialization do you mean?

Thanks

**Comment by hannesj** [comment]
Sorry, serialization is not the correct word, but coercion.

Eg. when doing the following query:

    query Stops {
        stops(first: 1) {
            edges {
                cursor node {
                    stop {
                        id
                    }
                }
            }
        }
    }

I get the following response:

    {
        "stops": {
            "edges": [{
                "cursor": "ConnectionCursor{value='c2ltcGxlLWN1cnNvcjA='}",
                "node": {
                    "stop": {
                        "id": "U3RvcDphZ2VuY3k6ZW50cmFuY2VfYg=="
                    }
                }
            }]
        }
    }

Instead of the correct one:


    {
        "stops": {
            "edges": [{
                "cursor": "c2ltcGxlLWN1cnNvcjA=",
                "node": {
                    "stop": {
                        "id": "U3RvcDphZ2VuY3k6ZW50cmFuY2VfYg=="
                    }
                }
            }]
        }
    }


This is due to [this](https://github.com/andimarek/graphql-java/blob/master/src/main/java/graphql/Scalars.java#L76) executing [this code](https://github.com/andimarek/graphql-java/blob/master/src/main/java/graphql/relay/ConnectionCursor.java#L36) instead of [this](https://github.com/andimarek/graphql-java/blob/master/src/main/java/graphql/relay/ConnectionCursor.java#L12)

**Comment by andimarek** [comment]
ok thanks ... that makes it more clear. I will have a look at in detail.

Just a quick thought: I'm not sure the problem is the coercion of  the string. Maybe the graphql schema is not correct: The cursor field should not be of type String, but maybe of type Connection? (I maybe totally wrong ;-) )

**Comment by hannesj** [comment]
According to the [specification](https://facebook.github.io/relay/graphql/connections.htm#sec-Cursor) it could be a custom scalar type, so we could just make ConnectionCursor extend GraphQLScalarType.

**Comment by andimarek** [comment]
Thanks for the link ... these are indeed the details I have missed in the first prototype. It might take me a few days to look at in more detail .. sorry for the delay.

**Comment by andimarek** [comment]
Yes,

the problem is indeed that the type of the `cursor` field is declared as String. So every Object in coerced into `toString()`.

Probably a custom scalar type might be the best solution, but as a quick fix I changed the `toString` of `ConnectionCursor`.

Does this for now solve you problem?

Thanks

**Comment by hannesj** [comment]
Thanks, works perfectly now
