### ISSUE TITLE
GraphQLInputObject wrapped in GraphQLList not parsed correctly

### ISSUE THREAD

**Issue by weebl2000** [andimarek/graphql-java#27]
For example:
```
@Component
public class SpaceInviteInputType implements TypeDefinition<GraphQLInputObjectType> {

    @Override
    public GraphQLInputObjectType getType( Schema schema ) {
        return GraphQLInputObjectType.newInputObject()
                .name( getName() )

                .field( newInputObjectField()
                        .name( "invitee" )
                        .type( new GraphQLNonNull( Scalars.GraphQLString ) )
                        .build() )

                .field( newInputObjectField()
                        .name( "rights" )
                        .type( new GraphQLList( Scalars.GraphQLString ) )
                        .build() )

                .build();
    }

}
```
And wrapping this in a GraphQLList is not parsed correctly.
```
                .argument( newArgument()
                        .name( "newRights" )
                        .type( new GraphQLList( schema.type( SpaceInviteInputType.class ) ) )
                        .build() )
```

Throwing a TypeValidationMisMatch exception.

When just using the ObjectInput directly, it works.

**Comment by andimarek** [comment]
Can you give an example request which is rejected?

Thanks

**Comment by weebl2000** [comment]
Complete query looked like this: SpaceInviteInput is the last object

```
{"query":"mutation event($space: ID!, $newRights: SpaceInviteInput[]!) { res: updateRights(id: $space, newRights: $newRights) {\n                        id\n                    } }","variables":"{\"space\":\"sIp2evFViScOvu_IZ4pEdnw\",\"newRights\":[{\"invitee\":\"wessel.nieboer@onior.com\",\"rights\":[\"READ\"]}]}"}
```

**Comment by andimarek** [comment]
The problem is the declaration of the variable type: `SpaceInviteInput[]!`.
An array is declared as `[type]` in graphql. So you probably meant `[SpaceInviteInput]!`. But even this will not work (I think), because `newRights` is not declared as NonNull. 

So you could just change the variable to `[SpaceInviteInput]` or change the schema, so that `newRights` is NotNull. Both ways should be fine.

I'm currently looking into the problem, that `SpaceInviteInput[]!` is not reported as an error. This shouldn't be happen.

**Comment by andimarek** [comment]
Hi,

I improved the error handling in this commit: https://github.com/andimarek/graphql-java/commit/fb53067cc862c654046d555863093c67edf76afa

So now you get directly an error, when you try executing something like `A[]`.

**Comment by andimarek** [comment]
@weebl2000 Could you solve your problem? I would close in this case. Thanks

**Comment by weebl2000** [comment]
Thanks for looking into it.
