### ISSUE TITLE
Not implemeting Required Arguments properly

### ISSUE THREAD

**Issue by tberman** [andimarek/graphql-java#30]
According to the spec (https://facebook.github.io/graphql/#sec-Required-Arguments), required arguments are implemented by marking an argument as NotNull. Execution without passing in an argument for a NotNull argument should throw an error.

**Comment by andimarek** [comment]
Hi,

I added a test for a missing argument.

https://github.com/andimarek/graphql-java/commit/1bc181089b5d8933bbb19cb6e1e09fd7576a7bb5#diff-3eca2508c3f86d5d839beca2e0e520faR132

I get a ValidationError, so it seems to work.

Did you mean this?

Thanks

**Comment by tberman** [comment]
Yes, I am an idiot. Ignore me please!
