### ISSUE TITLE
graphql-java on android:  DexException

### ISSUE THREAD

**Issue by andimarek** [andimarek/graphql-java#4]
Reported by @parallelcross (via twitter)
"DexException: Multiple dex files define Lorg/abego/treelayout/Configuration$AlignmentInLevel;"

**Comment by andimarek** [comment]
@parallelcross Could you please try the latest development build '2015-08-01T00-17-47'? (How to include this in your project here: https://github.com/andimarek/graphql-java#development-build)

I updated the dependency to antlr 4.5.1, which itself removed the unnecessary dependency to org.abego.treelayout. I hope this will fix your issue.

**Comment by parallelcross** [comment]
Thanks again. It says it can't find the dependency `compile 'com.graphql-java:graphql-java:2015-08-01T00-17-47'`

**Comment by parallelcross** [comment]
I did download the jar from bintray. I don't get the `DexException` anymore, but I do get:

```java.lang.NoClassDefFoundError: Failed resolution of: Lorg/slf4j/LoggerFactory;```

**Comment by parallelcross** [comment]
I added the slf4j dependency and was able to get past the `NoClassDefFoundError`. I now get:

```java.lang.NoClassDefFoundError: graphql.parser.antlr.GraphqlLexer
            at graphql.parser.Parser.parseDocument(Parser.java:18)
            at graphql.GraphQL.execute(GraphQL.java:63)
            at graphql.GraphQL.execute(GraphQL.java:54)
            at graphql.GraphQL.execute(GraphQL.java:46)
            at graphql.GraphQL.execute(GraphQL.java:42)
            at providerbrowser.wellmatch.com.providerbrowser.MainActivity.onCreate(MainActivity.java:39)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)```

**Comment by andimarek** [comment]
There seems to be a typo in your dependencies statement:

```groovy
dependencies {
       compile 'com.graphql-java:graphql-java:2015-08-01T00-17-47'`
}
```

There is a "backtick character" at the end of the line.

This should give you graphql-java, slf4j and the [antlr-runtime](http://search.maven.org/#artifactdetails%7Corg.antlr%7Cantlr4-runtime%7C4.5.1%7Cjar)  jar.

So you need all three jar files to run graphql-java.  A missing antr-runtime might explain you last Exception.

**Comment by parallelcross** [comment]
Sorry, that was just me mis-typing the dependency, the back tick wasn't in my build.gradle. I still can't resolve the dependency.

![screen shot 2015-08-01 at 2 03 16 pm](https://cloud.githubusercontent.com/assets/95728/9023180/5177e072-3856-11e5-9925-74bd013d0edc.png)

**Comment by andimarek** [comment]
ok .... what is the error message you get?

**Comment by andimarek** [comment]
I just realised that you of course  also need `mavenCentral()` as repository.

Do you have also 

```groovy

repositories {
    mavenCentral()
}

```

anywhere in your build file?

**Comment by parallelcross** [comment]
That did it. I was able to confirm the the library is working for me now. Thanks.

**Comment by andimarek** [comment]
Cool ... thanks a lot for your feedback. I also updated the README.

I will close this issue. Please open a new one, if you have any other problems/feedback.

**Comment by IHNEL** [comment]
I got the same error although already set mavenCentral()
`Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lorg/antlr/v4/runtime/ANTLRErrorListener;`

**Comment by dminkovsky** [comment]
What version are you using?

чт, 1 дек. 2016 г. в 21:07, IHNEL <notifications@github.com>:

**Comment by IHNEL** [comment]
I use v2.2.0:  compile 'com.graphql-java:graphql-java:2.2.0'

**Comment by dminkovsky** [comment]
I am sorry I am not sure then why you are having this error. Maybe google
for "android debug antlr runtime?"

чт, 1 дек. 2016 г. в 21:32, IHNEL <notifications@github.com>:

I use v2.2.0: compile 'com.graphql-java:graphql-java:2.2.0'

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/graphql-java/graphql-java/issues/4#issuecomment-264357532>,
or mute the thread

**Comment by IHNEL** [comment]
I did google but no solution help. This is my full gradle:
(I also put `mavenCentral()` on project level gradle ). I can sync the libraries without error, but I can't run the app.

````
apply plugin: 'com.android.application'
apply plugin: 'me.tatarka.retrolambda'
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"
    defaultConfig {
        applicationId "photos.waldo.demo"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
dependencies {
    // general
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:design:25.0.1'

    //GraphQL
    compile 'com.graphql-java:graphql-java:2.2.0'

    //reactive programming
    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'io.reactivex:rxjava:1.1.6'

    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    testCompile 'junit:junit:4.12'
}

```

**Comment by IHNEL** [comment]
I fixed this by:
`compile('com.graphql-java:graphql-java:2.2.0') {
        exclude group: 'org.antlr'
    }
`

**Comment by dminkovsky** [comment]
Oh wow I am sorry—I thought 2.2.0 had a fix for #225 (
https://github.com/graphql-java/graphql-java/issues/225), which is the
issue you experienced, but that fix was merged just after 2.2.0 was
released. That was why I asked you which version you were on. Anyway, I
hope you didn't waste too much time. The next release will have this patch
and you won't have to have this exclude in your build.

**Comment by IHNEL** [comment]
Thanks
Im really new on GraphQL, so many new things to learn. You guys did a great job.

**Comment by dminkovsky** [comment]
Thank you!
