### ISSUE TITLE
Add support for nullable fields in input

### ISSUE THREAD

**Issue by dieterwachters** [andimarek/graphql-java#41]
Hi,
I ran into a problem with mutations where we have a complex input object where not all fields need to be filled in. In out API, fields that are not set will be ignored during the update. This way we have a 'patch' instead of a full replace functionality.
This caused some nullpointers in the ValuesResolver class.
I have a patch, but cannot seem to attach it because I don't have write permissions in the repo. 

Kind regards,

**Comment by andimarek** [comment]
Hi,

if you have a patch, I would recommend that you open a Pull Request.

Thanks

**Comment by andimarek** [comment]
This should be solved with the latest dev build.
