### ISSUE TITLE
1.3 version?

### ISSUE THREAD

**Issue by Hellblazer** [andimarek/graphql-java#43]
Is there a 1.3 version in the future?  There's been a lot of great work on the project, a lot of excellent fixes.  Are you considering cutting another released version soon?

**Comment by andimarek** [comment]
Yes, you are right ... it makes sense to release a version 1.3.

I will try to do it around the next weekend.

Thanks for your input.

**Comment by Hellblazer** [comment]
Cool.

And thanks for this project ;)

**Comment by andimarek** [comment]
Is now released ... therefore I close this issue.
