### ISSUE TITLE
Introspection query not finding GraphQLInputObjectType when declared in hierarchical way

### ISSUE THREAD

**Issue by naveensenagari** [andimarek/graphql-java#50]
Hello,

Introspection query is not loading childInputObjecttype when InputObjects are declared in hierarchical way. i.e when I declare an GraphQLInputObjectType with in another GraphQLInputObjectType, its not recognizing the child InputObjectType. Would you please suggest a fix for this issue.

Parent{
    Child child;
}

Child{
     field a;
     field b;
}

**Comment by naveensenagari** [comment]
I saw fix for the above issue in current development jar (2015-11-15T12-15-10) . Can you please let me know when can I expect new jar version (i.e graphql-java-1.4) to consume.

Regards,

**Comment by andimarek** [comment]
Thanks for reporting this error.

In general I would recommend that you use the latest development jar. 

If that is not possible you will probably have to wait another few weeks. I will try to release a new version in this year.

I'm closing this issue because the bug is already fixed.
