### ISSUE TITLE
Subscriptions on the roadmap?

### ISSUE THREAD

**Issue by dbryand** [andimarek/graphql-java#51]
Hi--thanks for the great work on this lib. Any plan to add support for subscriptions?

http://graphql.org/blog/subscriptions-in-graphql-and-relay/

**Comment by andimarek** [comment]
As I currently understand it, the only thing this library could do, is to call a provided function which basically says: Register this subscription. The main work how the the data is then delivered, is out of scope and app depended. Is this your expectation?

So yes ... I think Subscriptions will be added. But currently subscriptions are not in the graphql spec.

**Comment by dbryand** [comment]
I actually don't even need the `subscriptionType`, but I'm trying to keep up my [introspectionQuery](https://github.com/graphql/graphql-js/blob/master/src/utilities/introspectionQuery.js) that I use to generate `schema.json` update to date with [graphql-js](https://github.com/graphql/graphql-js).

The problem is that the newer [introspectionQuery](https://github.com/graphql/graphql-js/blob/master/src/utilities/introspectionQuery.js) has a query for `subscriptionType { name }` which thows a `Validation error of type FieldUndefined: Field subscriptionType is undefined` when I run it:

```
  query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
...
```

**Comment by andimarek** [comment]
Hi,

I just added a small change to at least support the `subscriptionType` field in the query: https://github.com/andimarek/graphql-java/commit/3a96047a25c46db27f4c1743755215c0982b35ab

Could you give it try with the latest build to see if it solved your problem?

Thanks

**Comment by andimarek** [comment]
@dbryand Can you confirm that this issue is resolved? Thanks

**Comment by hbeaufils** [comment]
Hi,

I had the same issue, but I confirm it's currently fixed on master.

Thanks!

**Comment by andimarek** [comment]
@hbeaufils Thanks for this info. I'm closing this issue.
