### ISSUE TITLE
Schema introspection on the server

### ISSUE THREAD

**Issue by jasiekkrk** [andimarek/graphql-java#52]
Hi,
is it (or will be) possible to do schema introspection on the server? Something like this
http://stackoverflow.com/questions/32178553/relay-app-how-to-introspect-schema-on-server

We`ll need it to build schema on the server based on introspection query, and call remote GraphQL endpoint from Java.

Thanks,
Andrzej

**Comment by andimarek** [comment]
Hi,

for an example how to build an http endpoint which executes graphql requests have a look at this:

https://github.com/andimarek/todomvc-relay-java/blob/master/src/main/java/todomvc/GraphQLController.java

Schema Introspection in general is already available. But how you call it, http or something else, is totally up to you and not in the scope of this library.

I hope that helps.

Regards,
Andi

**Comment by jasiekkrk** [comment]
Hi,
Thanks for reply. I understand how to execute query. What I`m missing is how to build graphql schema, based on introspected JSON to be able to execute queries on remote servers (from Java).
GraphQL JS has utlis which can build such schema from json file (http://graphql.org/docs/api-reference-utilities/#buildastschema)

Regards,
Andrzej

**Comment by andimarek** [comment]
Ok ...I misunderstood you ... yes, this is not possible currently...you're right.

I would like to understand your use case: Why do you need a remote schema to execute a query?

**Comment by jasiekkrk** [comment]
We have scenario like this
End user (browser)  uses React+ Relay+GraphQL and connects to our backend, which defines schema build using remote schema, and adds our custom fields. So we have to execute query on remote server to get the data, and mix them with custom data loaded from database.


Browser <---> Our graphQl server <-----> remote graphql Server


Probably for the time being we will use node to see if it`s even possible with reference js implementation.

Thanks a lot, 
Andrzej
