### ISSUE TITLE
How to pass List of string to query?

### ISSUE THREAD

**Issue by edsalat** [andimarek/graphql-java#55]
Please could provide info how to pass list of string to query?
No matter what I have tried, getting " description='Unknown type List'}]" error message.
Call is like this:  
List<String> ids = new LinkedList<String>();  ids.add("22222"); args.put("id", ids);
and Query:
" query FetchIssuer($id: List) { user ( id:$id) { firstName, lastName, id } }"

**Comment by andimarek** [comment]
List is not a valid type. I think you want "[String]".

**Comment by edsalat** [comment]
Thank you! It works
