### ISSUE TITLE
Access object from "parent" data fetcher

### ISSUE THREAD

**Issue by nikolajosipovic** [andimarek/graphql-java#56]
Hi,

Thank you for this awesome lib : )

Having a schema like:

```
Dogs
  type(GraphQLList(DogType))
  dataFetcher(DogsDatafetcher)

DogType
  name
  breed (BreedDatafetcher)
```

Is there some nice way BreedDatafetcher could communicate with the DogsDatafetcher to get a DogObject retrieved there to provide the data?

What I did is return the DogObject alongside other data returned from DogsDatafetcher.
Then in BreedDatafetcher i would get the DogObject using:
`DogObject dog = ((Map<String, DogObject>)(environment.getSource())).get("DOG_OBJECT")`

`{ dogs { name breed }}`

**Comment by andimarek** [comment]
Hi,

I think you solution is the preferred (or currently the only) way. If you want to access some contextual data you access the source object  and the previous datafetcher is responsible to provide the informations you want to access.

**Comment by nikolajosipovic** [comment]
Thanks a lot Andi
