### ISSUE TITLE
Support for recursive Objects

### ISSUE THREAD

**Issue by nmn** [andimarek/graphql-java#65]
Very often there is a need for Nested structures in data models.

Example 1: Comments:

```
GraphQLObjectType commentType = newObject()
                        .name("Comment")
                        .field(newFieldDefinition()
                                .type(new GraphQLList(commentType))
                                .name("replies")
                                .build())
                        .build();
```

Example 2: Friends:

```
GraphQLObjectType personType = newObject()
                        .name("Person")
                        .field(newFieldDefinition()
                                .type(new GraphQLList(commentType))
                                .name("friends")
                                .build())
                        .build();
```

These fairly common use-cases current seem impossible with GraphQL-Java. This is because the type field cannot be null. GraphQL-js gets around this problem by letting you define your fields as a function:

```
var CommentsType = new GraphQLObjectType({
  name: 'Comments',
  fields: () => ({
    humanName: {type: GraphQLString},
    replies: {type: new GraphQLList(GreetingsType)}
  }),
});
```

Is something like this possible with GraphQL-java? If not can it be added??

I recommend, overloading the `.type` to accept a lambda Function. I'll try to make a pull request, that fill probably not work, but with your help it may be possible to make it work.

**Comment by andimarek** [comment]
I think this solves your problem:

https://github.com/andimarek/graphql-java#recursive-type-references

**Comment by nmn** [comment]
This is awesome. Thanks!
