### ISSUE TITLE
Boolean property via getter

### ISSUE THREAD

**Issue by nikolajosipovic** [andimarek/graphql-java#83]
Hi,

Do you think the following behaviour is incorrect:

Field name: `isSelected`
Usual java getter: `isSelected()`
GraphQl expected getter: `isIsSelected`

File `PropertyDataFetcher.java`, method `getPropertyViaGetter`

**Comment by andimarek** [comment]
Hi,

no I don't think so: By Java convention the getter for a boolean is named `is<PropertName>` ... so `isIsSelected` is correct.

You might wanna change the field to just selected.

**Comment by nikolajosipovic** [comment]
ok thanks, closing
