### ISSUE TITLE
Input GraphQlFloat is Float when read from GraphQl variables and Double when input directly

### ISSUE THREAD

**Issue by buma** [andimarek/graphql-java#86]
I'm working on GraphQl for R5 and have query like that:
```javascript
query requestPlan($fromTime: ZonedDateTime!, $fromLat:Float!, $fromLon:Float!) {
  plan(fromLat:$fromLat, fromLon:$fromLon,
  toLat:46.55680201284476,toLon:15.626914501190184,
  fromTime:$fromTime, toTime:"2015-02-05T10:30+01:00" directModes:[CAR,WALK],
  accessModes:[WALK, BICYCLE], egressModes:[WALK],
transitModes:[BUS]) {
```

Problem is that when I input values for toLat, fromLat, fromLon and toLon which are GraphQL Floats directly I read them on Java side as Doubles. But If I use GraphQL variables I read them as Floats.

Any idea why?

I'm using version 2016-02-01T07-19-40.

**Comment by andimarek** [comment]
This is a bug: I recently changed the impl for GraphQLFloat to return doubles to match the spec: https://github.com/andimarek/graphql-java/commit/3062e2b48503ec02c9e2364d4c063baa798352a4 

But the literal is currently still interpreted as float .. this needs to be changed to double.

**Comment by andimarek** [comment]
This should be now fixed with this commit: https://github.com/andimarek/graphql-java/commit/113a9d01891084649f144c6fc5980c5d5d55feb6

**Comment by buma** [comment]
Thanks for quick fix. It works great now.
