### ISSUE TITLE
Redefining a field should fail

### ISSUE THREAD

**Issue by tuukka** [andimarek/graphql-java#88]
Currently, it's possible to re-define a field with a name that was already defined. I'd expect this to fail as it indicates an error in the source. After a cursory look, an assertion in the constructor of GraphQLObjectType might be necessary.

**Comment by andimarek** [comment]
Hi,

yes, I would also think it would be good to fail early. Would you willing to create a PR for that?

Thanks

**Comment by andimarek** [comment]
This is implemented by #102
