### ISSUE TITLE
any plan to config schema by xml?

### ISSUE THREAD

**Issue by hanmu** [andimarek/graphql-java#90]
Currently,we config type system & schema by program way ,like StarWarsSchema.java. So do u have a plan to config the schema by xml ?

**Comment by andimarek** [comment]
Hi,

I'm sorry, but I have no plan currently to add xml schema configuration.

Andi

**Comment by hanmu** [comment]
ok~thank you for your replay.

**Comment by andimarek** [comment]
Closing, because nothing todo here currently.
