### ISSUE TITLE
How to pass arrays of ids 

### ISSUE THREAD

**Issue by edsal2** [andimarek/graphql-java#92]
If I would like to extract multiple objects how to pass multiple ids?
i.e   {profile(id:"33", id:"44"){LastName, FirstName}}

**Comment by okorz001** [comment]
You can refactor your schema to `profile(ids: [33, 44]){...}`

**Comment by andimarek** [comment]
Thanks @okorz001 for answering: I would suggest the same. 

@edsal2 I'm closing this issue. If you have any more questions about how to use graphql-java, please consider posting it on the mailing-list (https://groups.google.com/forum/#!forum/graphql-java).
