### ISSUE TITLE
Suport for Longs

### ISSUE THREAD

**Issue by drkarl** [andimarek/graphql-java#98]
I know the GraphQL spec doesn't have support for longs, only for ints (32-bit signed integer) https://facebook.github.io/graphql/#sec-Built-in-Scalars, but since you already have a GraphQLLong, you might as well add full support for them.

Currently the ANTLR parser correctly parses integer numbers into an IntVal, and then in `GraphqlAntlrToLanguage.getValue()` you do 

```java
if (ctx.IntValue() != null) {
            IntValue intValue = new IntValue(Integer.parseInt(ctx.IntValue().getText()));
            newNode(intValue, ctx);
            return intValue;
        } else ...
```

I think you could just create a LongValue price you could do something like

```java
if (ctx.IntValue() != null) {
			try {
				Integer value = Integer.parseInt(ctx.IntValue().getText());
				IntValue intValue = new IntValue(value);
            	newNode(intValue, ctx);
            	return intValue;
			} catch (NumberFormatException e) {
				Long value = Long.parseLong(ctx.IntValue().getText());
				LongValue longValue = new LongValue(value);
            	newNode(longValue, ctx);
            	return longValue;
			}
        } else  ...
```

and then change `Scalars.GraphQLLong` so that it coerces from a LongVal into a Long rather than expect a StringVal.

**Comment by okorz001** [comment]
See #93 and #94.

**Comment by drkarl** [comment]
Looks good, it's been open for a while!!

**Comment by andimarek** [comment]
Long is now supported, see #94.
